INSERT INTO voti(cognome, nome, materia, voto)
VALUES('Marchetto', 'Francesco', 'Matematica', 10),
('Visentini', 'Nicolò', 'Informatica',7),
('Poli','Alessio','Sistemi', 6),
('Gianesella','Riccardo','Matematica',4,5),
('Marchetto', 'Francesco', 'Matematica', 2),
('Poli','Alessio','Informatica', 9),
('Gianesella','Riccardo','Storia',4),
('Visentini', 'Nicolò', 'Italiano',9),
('Poli','Alessio','Religione', 0),
('Gianesella','Riccardo','Italiano',8),
('Poli','Alessio','Tpsit', ),
('Visentini', 'Nicolò', 'Gpoi',6),
('Gianesella','Riccardo','Gpoi',5,5),
('Marchetto', 'Francesco', 'Storia', 1),
('Marchetto', 'Francesco', 'Italiano', 7);